### ISSUE TITLE
Can you also publish this plug-in to https://open-vsx.org

### ISSUE THREAD

**Issue by MarkHoo** [florinpatrascu/vscode-elixir-snippets#25]
Hello, could you please publish this plugin on this platform so that it can be installed and used in the online version of vscode? If so, that would be great! Thank you very much!

**Comment by florinpatrascu** [comment]
sure thing, thank you for the suggestion.

**Comment by florinpatrascu** [comment]
_eclipse is not seeing my github account and the UEX is probable the unfriendliest in the recent memory. Glad they're so careful with asking for so many personal details. Any way, I'll wait until they fix my profile, and then I'll publish it. Sorry for delay_ /vent

**Comment by florinpatrascu** [comment]
https://open-vsx.org/extension/florinpatrascu/vscode-elixir-snippets
